# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.base.exchange import Exchange
from ccxt.base.errors import ExchangeError
from ccxt.base.errors import DDoSProtection


class xmeta(Exchange):

    def describe(self):
        return self.deep_extend(super(xmeta, self).describe(), {
            'id': 'xmeta',
            'name': 'xmeta',
            'countries': ['MN'],
            'rateLimit': 500,
            'requiresWeb3': False,
            'certified': False,
            # new metainfo interface
            'has': {
                'cancelOrder': False,
                'CORS': None,
                'createOrder': False,
                'fetchBalance': False,
                'fetchBidsAsks': False,
                'fetchClosedOrders': False,
                'fetchCurrencies': False,
                'fetchDepositAddress': False,
                'fetchDeposits': False,
                'fetchMarkets': False,
                'fetchMyTrades': False,
                'fetchOHLCV': False,
                'fetchOpenOrders': False,
                'fetchOrder': False,
                'fetchOrderBook': False,
                'fetchOrders': False,
                'fetchTicker': False,
                'fetchTickers': True,
                'fetchTrades': False,
                'fetchWithdrawals': False,
                'withdraw': None,
            },
            'urls': {
                'test': {
                    'market': 'https://exchange-proxy.krypto.mn/x-meta',
                    'public': 'https://exchange-proxy.krypto.mn/x-meta',
                },
                'logo': 'https://user-images.githubusercontent.com/1294454/67288762-2f04a600-f4e6-11e9-9fd6-c60641919491.jpg',
                'api': {
                    'proxy': 'https://exchange-proxy.krypto.mn/x-meta',
                },
                'www': 'https://www.x-meta.com',
                'doc': 'https://www.x-meta.com',
            },
            'api': {
                'proxy': {
                    'get': [
                        'tickers',
                        'ohlcv',
                    ],
                },
            },
            'timeframes': {
                '1m': '1m',
                '5m': '5m',
                '15m': '15m',
                '30m': '30m',
                '1h': '1h',
                '2h': '2h',
                '4h': '4h',
                '6h': '6h',
                '12h': '12h',
                '1d': '1d',
            },
        })

    async def fetch_tickers(self, symbols=None, params={}):
        response = await self.proxyGetTickers(params)
        # {
        #     "code": 0,
        #     "msg": "Success",
        #     "data": {
        #         "list": [
        #             {
        #                 "symbol": "IHC_BUSD",
        #                 "assetId": 568,
        #                 "type": 2,
        #                 "baseAsset": "IHC",
        #                 "name": "Inflation Hedging Coin",
        #                 "logoUrl": "https://www.x-meta.com/static/bankicon/IHC_Icon.png",
        #                 "quoteAsset": "BUSD",
        #                 "price": "0.00072119",
        #                 "volume": "181553667.4028889300",
        #                 "baseVolume": "0",
        #                 "amount": "130972.4742196600",
        #                 "quoteVolume": "0",
        #                 "change24h": "0.16249548",
        #                 "low": "0.00072002",
        #                 "high": "0.00072997",
        #                 "open": "0.00072002",
        #                 "close": "0.00072119",
        #                 "time": 1645259100005,
        #                 "klineUrl": "",
        #                 "klineImageUrl": ""
        #             }
        #         ]
        #     },
        #     "timestamp": 1645259150941
        # }
        return self.parse_tickers(response['data']['list'], symbols)

    def parse_ticker(self, ticker, market=None):
        timestamp = self.safe_integer(ticker, 'time')
        # {
        #     symbol: 'IHC_BUSD',
        #     assetId: '568',
        #     type: '2',
        #     baseAsset: 'IHC',
        #     name: 'Inflation Hedging Coin',
        #     logoUrl: 'https://www.x-meta.com/static/bankicon/IHC_Icon.png',
        #     quoteAsset: 'BUSD',
        #     price: '0.00072121',
        #     volume: '182803667.4028889300',
        #     baseVolume: '0',
        #     amount: '131873.9867196500',
        #     quoteVolume: '0',
        #     change24h: '0.16527318',
        #     low: '0.00072002',
        #     high: '0.00072997',
        #     open: '0.00072002',
        #     close: '0.00072121',
        #     time: '1645259400004',
        #     klineUrl: '',
        #     klineImageUrl: ''
        # }
        symbolsSplitted = ticker['symbol'].split('_')
        symbol = '/'.join(symbolsSplitted)
        return {
            'symbol': symbol,
            'timestamp': timestamp,
            'datetime': self.iso8601(timestamp),
            'high': self.safe_number(ticker, 'high'),
            'low': self.safe_number(ticker, 'low'),
            'bid': None,
            'bidVolume': None,
            'ask': None,
            'askVolume': None,
            'vwap': None,
            'open': self.safe_number(ticker, 'open'),
            'close': self.safe_number(ticker, 'price'),
            'last': self.safe_number(ticker, 'price'),
            'previousClose': None,
            'change': None,
            'percentage': None,
            'average': None,
            'baseVolume': self.safe_number(ticker, 'amount') / self.safe_number(ticker, 'price'),
            'quoteVolume': self.safe_number(ticker, 'amount'),
            'info': ticker,
        }

    async def fetch_ohlcv(self, symbol, timeframe='1d', since=None, limit=None, params={}):
        id = symbol.replace('/', '_')
        request = {
            'symbol': id,
            'interval': self.timeframes[timeframe],
        }
        if since is None:
            request['startTime'] = int(self.milliseconds() / 1000 - 48 * 60 * 60)
        else:
            request['startTime'] = since
        if limit is None:
            request['endTime'] = int(self.milliseconds() / 1000)
        else:
            duration = self.parse_timeframe(timeframe)
            request['endTime'] = int(self.sum(request['startTime'], limit * duration))
        response = await self.proxyGetOhlcv(request)
        # {
        #     "code": 0,
        #     "msg": "Success",
        #     "data": {
        #       "list": [
        #         [
        #           "1673913600000",
        #           "0.0000670000",
        #           "0.0000690000",
        #           "0.0000660000",
        #           "0.0000670000",
        #           "423001985.1347635700",
        #           "1673999999999",
        #           "28336.1027785800",
        #           "170",
        #           "164415353.4837635700",
        #           "11124.6813104000",
        #           ""
        #         ],
        #     }
        # }
        return self.parse_ohlcvs(response['data']['list'], symbol, timeframe, since, limit)

    def parse_ohlc_vs(self, ohlcvs, market=None, timeframe='1m', since=None, limit=None):
        result = []
        for i in range(0, len(ohlcvs)):
            result.append(self.parse_ohlcv(ohlcvs[i], market))
        sorted = self.sort_by(result, 0)
        return sorted

    def parse_ohlcv(self, ohlcv, market=None):
        ohlcv[0] = int(ohlcv[0])
        ohlcv[1] = int(ohlcv[1])
        ohlcv[2] = int(ohlcv[2])
        ohlcv[3] = int(ohlcv[3])
        ohlcv[4] = int(ohlcv[4])
        ohlcv[5] = int(ohlcv[5])
        return ohlcv[0:6] if isinstance(ohlcv, list) else ohlcv

    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.urls['api'][api]
        url += '/' + path
        if params:
            url += '?' + self.urlencode(params)
        return {'url': url, 'method': method, 'body': body, 'headers': headers}

    def handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody):
        if code == 503:
            raise DDoSProtection(self.id + ' ' + str(code) + ' ' + reason + ' ' + body)
        if response is None:
            return  # fallback to default error handler
        if 'code' in response:
            status = self.safe_string(response, 'code')
            if status == '1':
                message = self.safe_string(response, 'msg')
                feedback = self.id + ' ' + body
                self.throw_exactly_matched_exception(self.exceptions, message, feedback)
                raise ExchangeError(feedback)
